defmodule Reporting.Report.Sheets.LedgerOverview.Columns.OperationName do
  def get(0),  do: "Transfer"
  def get(1),  do: "Limit Order Create"
  def get(2),  do: "Limit Order Cancel"
  def get(3),  do: "Call Order Update"
  def get(4),  do: "Fill Order"
  def get(5),  do: "Account Create"
  def get(6),  do: "Account Update"
  def get(7),  do: "Account Whitelist"
  def get(8),  do: "Account Upgrade"
  def get(9),  do: "Account Transfer"
  def get(10), do: "Asset Create Operation"
  def get(11), do: "Asset Update Operation"
  def get(12), do: "Asset Update Bitasset"
  def get(13), do: "Asset Update Feed Producers"
  def get(14), do: "Asset Issue"
  def get(15), do: "Asset Reserve"
  def get(16), do: "Asset Fund Fee Pool"
  def get(17), do: "Asset Settle"
  def get(18), do: "Asset Global Settle"
  def get(19), do: "Asset Publish Feed"
  def get(20), do: "Witness Create Operation"
  def get(21), do: "Witness Update Operation"
  def get(22), do: "Proposal Create Operation"
  def get(23), do: "Proposal Update Operation"
  def get(24), do: "Proposal Delete Operation"
  def get(25), do: "Withdraw Permission Create"
  def get(26), do: "Withdraw Permission Update"
  def get(27), do: "Withdraw Permission Claim"
  def get(28), do: "Withdraw Permission Delete"
  def get(29), do: "Committee Member Create"
  def get(30), do: "Committee Member Update"
  def get(31), do: "Committee Member Update Global Parameters"
  def get(32), do: "Vesting Balance Create"
  def get(33), do: "Vesting Balance Withdraw"
  def get(34), do: "Worker Create"
  def get(35), do: "Custom Operation"
  def get(36), do: "Assert Operation"
  def get(37), do: "Balance Claim"
  def get(38), do: "Override Transfer"
  def get(39), do: "Transfer to Blind"
  def get(40), do: "Blind Transfer"
  def get(41), do: "Transfer from Blind"
  def get(42), do: "Asset Settle Cancel"
  def get(43), do: "Asset Claim Fees"
  def get(44), do: "FBA Distribute"
  def get(45), do: "Bid Collateral"
  def get(46), do: "Execute Bid"
  def get(47), do: "Asset Claim Pool"
  def get(48), do: "Asset Update Issuer"
  def get(49), do: "Custom Authority Create"
  def get(50), do: "Custom Authority Update"
  def get(51), do: "Custom Authority Delete"
  def get(_),  do: "Undefined"
end
